version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=077708451457.dkr.ecr.ap-south-1.amazonaws.com/node-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $077708451457.dkr.ecr.ap-south-1.amazonaws.com/node-app:latest .
      - docker tag $077708451457.dkr.ecr.ap-south-1.amazonaws.com/node-app:latest $077708451457.dkr.ecr.ap-south-1.amazonaws.com/node-app:$node-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $077708451457.dkr.ecr.ap-south-1.amazonaws.com/nodegit:$node-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"node-app","imageUri":077708451457.dkr.ecr.ap-south-1.amazonaws.com/node-app:$node-app:latest"}]' $077708451457.dkr.ecr.ap-south-1.amazonaws.com/nodegit:$node-app:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
