version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - REPOSITORY_URI=881863418650.dkr.ecr.us-east-1.amazonaws.com/nodegit:latest
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $node-app:latest 881863418650.dkr.ecr.us-east-1.amazonaws.com/nodegit:latest .
      - docker tag $881863418650.dkr.ecr.us-east-1.amazonaws.com/nodegit:latest $node-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $881863418650.dkr.ecr.us-east-1.amazonaws.com/nodegit:latest $node-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"node-app","imageUri":881863418650.dkr.ecr.us-east-1.amazonaws.com/nodegit:latest $881863418650.dkr.ecr.us-east-1.amazonaws.com/nodegit:latest $node-app:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
