version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies.
      - npm install
      - pip install awscli --upgrade --user
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 881863418650.dkr.ecr.us-east-1.amazonaws.com $)
      - REPOSITORY_URL=881863418650.dkr.ecr.us-east-1.amazonaws.com/repo
  build:
    commands:
      - docker build -t node-app .
      - docker tag node-app:latest 881863418650.dkr.ecr.us-east-1.amazonaws.com/repo:latest   
      - docker push 881863418650.dkr.ecr.us-east-1.amazonaws.com/repo:latest
      - npm run build
  
artifacts:
  files:
    - '**/*'
