version: 0.2


phases:
  pre_build:
    commands:
      - pip install awscli --upgrade --user
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=881863418650.dkr.ecr.us-east-1.amazonaws.com/nodegit
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - echo $REPOSITORY_URI
      - echo $IMAGE_TAG
      - docker tag nodegit:v1$881863418650.dkr.ecr.us-east-1.amazonaws.com/nodegit:$v1 
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --rm -f Dockerfile -t nodegit:v1 .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:v1
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
